### ISSUE TITLE
Loading a numpy file gives error message, only after recipy import.

### ISSUE THREAD

**Issue by HannoSpreeuw** [recipy/recipy#83] opened 2015-09-14 12:18 UTC
Python 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Mar  6 2015, 12:03:53) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import recipy
recipy run inserted, with ID 0092d4ce-b552-4e96-a2bb-ea414974000b
>>> import numpy as np
>>> bp_Titan = np.load('bp_Titan.npy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hspreeuw/anaconda3/lib/python3.4/site-packages/recipy/utils.py", line 49, in f
    return wrapped(*args, **kwargs)
  File "/home/hspreeuw/anaconda3/lib/python3.4/site-packages/numpy/lib/npyio.py", line 393, in load
    return format.read_array(fid)
  File "/home/hspreeuw/anaconda3/lib/python3.4/site-packages/numpy/lib/format.py", line 606, in read_array
    array = numpy.fromfile(fp, dtype=dtype, count=count)
  File "/home/hspreeuw/anaconda3/lib/python3.4/site-packages/recipy/utils.py", line 48, in f
    function(args[arg_loc], source)
  File "/home/hspreeuw/anaconda3/lib/python3.4/site-packages/recipy/log.py", line 81, in log_input
    filename = os.path.abspath(filename)
  File "/home/hspreeuw/anaconda3/lib/python3.4/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/home/hspreeuw/anaconda3/lib/python3.4/posixpath.py", line 63, in isabs
    return s.startswith(sep)
AttributeError: '_io.BufferedReader' object has no attribute 'startswith'

**Comment by robintw** [comment] 2015-09-14 13:57
Thanks for reporting this - I think I know what the problem is, and I'll fix it ASAP.

**Comment by robintw** [comment] 2015-09-21 20:59
This has now been fixed in the latest version on Github. I will try and release a new version to PyPI soon, once a few other bugs have been ironed out.

**Closed** 2015-09-21 20:58 UTC
Labels: bug, hooks

**Comment by robintw** [comment] 2015-09-26 10:15
Just FYI, the latest version on PyPI (v0.2.0) now has this fix. Thanks for reporting it.

**Comment by HannoSpreeuw** [comment] 2015-09-26 14:33
Nice!
